# Generated by Django 6.1.1 on 2026-09-29 00:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodegaApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Área/Departamento')),
                ('codigo_area', models.CharField(max_length=10, unique=True, verbose_name='Código Áreas Jumbo (Ej: BOD-AP, SALA-01)')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción de Responsabilidades')),
            ],
            options={
                'verbose_name': 'Departamento / Área',
                'verbose_name_plural': 'Departamentos y Áreas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=12, unique=True, verbose_name='RUT Trabajador')),
                ('nombres', models.CharField(max_length=100, verbose_name='Nombres')),
                ('apellidos', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('cargo', models.CharField(max_length=100, verbose_name='Cargo (Ej: Bodeguero AP, Reponedor Sala, Supervisor)')),
                ('turno', models.CharField(choices=[('MAÑANA', 'Turno Mañana (07:00 - 15:00)'), ('TARDE', 'Turno Tarde (14:30 - 22:00)'), ('NOCHE', 'Turno Noche / Reposición (21:30 - 07:00)')], default='MAÑANA', max_length=20, verbose_name='Turno Asignado')),
                ('fecha_ingreso', models.DateField(verbose_name='Fecha de Ingreso')),
                ('activo', models.BooleanField(default=True, verbose_name='¿Trabajador Activo en Jumbo?')),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empleados', to='bodegaApp.departamento', verbose_name='Área de Trabajo')),
            ],
            options={
                'verbose_name': 'Trabajador Jumbo',
                'verbose_name_plural': 'Trabajadores Jumbo',
                'ordering': ['apellidos', 'nombres'],
            },
        ),
        migrations.DeleteModel(
            name='cargo',
        ),
    ]
