# Generated by Django 6.1.1 on 2026-09-29 01:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodegaApp', '0002_departamento_empleado_delete_cargo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Categoría de Producto')),
                ('pasillo', models.IntegerField(default=1, verbose_name='Pasillo de Exhibición en Sala')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías de Productos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_barras', models.CharField(max_length=20, unique=True, verbose_name='Código EAN / SKU')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre del Producto')),
                ('precio', models.IntegerField(verbose_name='Precio Venta Jumbo ($)')),
                ('stock_bodega', models.IntegerField(default=0, verbose_name='Stock en Bodega AP')),
                ('stock_sala', models.IntegerField(default=0, verbose_name='Stock en Sala de Ventas')),
                ('fecha_vencimiento', models.DateField(blank=True, null=True, verbose_name='Fecha Próxima de Vencimiento')),
                ('en_oferta', models.BooleanField(default=False, verbose_name='¿Producto en Oferta Jumbo?')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='bodegaApp.categoria', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos e Inventario',
                'ordering': ['nombre'],
            },
        ),
    ]
